### PR TITLE
Update descriptions on change and fix hot key starts

### LINKED ISSUE #67: Mod starts multiple times when hotkey is spammed
Mod starts multiple times when hotkey is spammed and mod is not active. It can only be fixed with a restart of Minecraft

### LINKED ISSUE #68: Item descriptions need to be refreshed in some UIs
The gui isn't reopened in eg. trade views thus the descriptions for items the other trade side adds into the windows don't have any description.
The new description needs to be loaded for all items when a new item is added (intending to add a summary on the confirm button)

### PR DESCRIPTION
**Pull request by Ekwav**
fixes #68 & fixes #67

Adds `/cofl dev` to quickly switch into development mode (using local backends)

### CODE REVIEW

File: src/main/java/de/torui/coflsky/CoflSkyCommand.java [hunk 1]
```diff
@@ -95,8 +95,13 @@ public void processCommand(ICommandSender sender, String[] args) throws CommandE
...
 					break;	
-				case "callback":
-					CallbackCommand(args);
+					case "callback":
+						CallbackCommand(args);
+						break;
+				case "dev":
+					CoflSky.Wrapper.initializeNewSocket("ws://localhost:8009/modsocket");
+					Config.BaseUrl = "http://localhost:5005";
+					System.out.println("entered dev mode");
```
Comment (ToruiDev) [inline src/main/java/de/torui/coflsky/CoflSkyCommand.java:104]: Should there be any indication that this requires a full restart to be able to connecto to the online servers again?

**Review by ToruiDev — COMMENTED** [review]
rest looks good

File: src/main/java/de/torui/coflsky/CoflSkyCommand.java (hunk 1 above)
Comment (Ekwav) [reply src/main/java/de/torui/coflsky/CoflSkyCommand.java]: made it toggle-able and write in chat where its connected to
